apiVersion: v1
kind: Service
metadata:
  name: sentinel-api-service
  labels:
    app.kubernetes.io/name: sentinel-ai
    app.kubernetes.io/component: api
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: sentinel-api
